# Generated by Django 3.1.7 on 2021-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Наименование продукта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('hide', models.BooleanField(blank=True, default=False, verbose_name='Продукт скрыт')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Коэффициент')),
                ('group', models.IntegerField(blank=True, default=0, verbose_name='Группа товара')),
            ],
        ),
    ]
