# Generated by Django 3.1.7 on 2021-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(default='', verbose_name='Текст статьи')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
    ]
